### ISSUE TITLE
Receive location?

### ISSUE THREAD

**Issue by pepa65** [psanford/wormhole-william-mobile#9]
Where was my received file saved to? It wasn't in downloads, and browsing around I couldn't find it. If you're not going to put it in Downloads, it would be great if a configuration option was available to specify the download location.
Otherwise, great app!

**Comment by psanford** [comment]
It should be in your downloads folder. What type of device are you using and what version of android is it on?

**Comment by pepa65** [comment]
Smartphone, Android 10. No notification, I'll try again right now. (Does it matter that there is a previous version with the same filename already there??)

**Comment by pepa65** [comment]
I just tried the other Android app, and it ran into this issue: https://github.com/pavelsof/mobile-wormhole/issues/12
Apparently Android 10+ is making it difficult... 👎🏻

**Comment by psanford** [comment]
Wormhole-william uses the download manager api. it doesn't directly access the filesystem. 

It works fine on my Pixel 5 running the latest stable Android 11 build.

**Comment by pepa65** [comment]
It's too bad, it would be an ideal use of the protocol. I'm getting an Android 11 device, so maybe it will work there.

**Comment by psanford** [comment]
Its going to be difficult to debug without more information. Can you pull the ADB logs from the device?

**Comment by pepa65** [comment]
I understand, I'll see what I can do, it sounds like quite an operation...

**Comment by ashwinvis** [comment]
I have the same issue. I don't see the file after the transfer is complete. I see that the "App info" window says "No permissions requested". Shouldn't it prompt for access to storage to write the files?

I have adb installed. Can you point me how to pull the logs?

**Comment by psanford** [comment]
Wormhole william uses the Download api and filepicker api so it does not need direct storage access. Can you share the details about your device? What is the manufacturer, model and Android version?

The easiest way to get the logs would be to first get the pid of the app and then pass that to `adb logcat`:
```  
$ adb shell pidof io.sanford.wormhole_william
2859
$ adb logcat --pid=2859
```
(replace `2859` with whatever pidof returns for your system). After you start the logcat send to your phone via magic wormhole to see what it logs.

**Comment by ashwinvis** [comment]
Fairphone 3, Android 10. Here are the logs:

```log
❯ adb logcat --pid=10624
--------- beginning of main
05-04 22:23:49.536 10624 10624 E ormhole_willia: Not starting debugger since process cannot load the jdwp agent.
05-04 22:23:49.576 10624 10624 I Perf    : Connecting to perf service.
05-04 22:23:49.683 10624 10644 I AdrenoGLES: QUALCOMM build                   : 994be9a, I75b52107df
05-04 22:23:49.683 10624 10644 I AdrenoGLES: Build Date                       : 05/28/20
05-04 22:23:49.683 10624 10644 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.10
05-04 22:23:49.683 10624 10644 I AdrenoGLES: Local Branch                     : 
05-04 22:23:49.683 10624 10644 I AdrenoGLES: Remote Branch                    : 
05-04 22:23:49.683 10624 10644 I AdrenoGLES: Remote Branch                    : 
05-04 22:23:49.683 10624 10644 I AdrenoGLES: Reconstruct Branch               : 
05-04 22:23:49.684 10624 10644 I AdrenoGLES: Build Config                     : S L 8.0.12 AArch64
05-04 22:23:49.737 10624 10644 I AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
05-04 22:23:49.790 10624 10649 W Gralloc3: mapper 3.x is not supported
05-04 22:34:48.651 10624 10651 I io.sanford.wormhole_william: recv clicked
05-04 22:34:57.251 10624 11272 I io.sanford.wormhole_william: Call NotifyDownloadManager
05-04 22:34:57.254 10624 11272 D wormhole: Download()
05-04 22:34:57.254 10624 11272 D wormhole: Download: register()
05-04 22:34:57.255 10624 10624 D wormhole: Download: onAttach()
05-04 22:34:57.269 10624 10624 D wormhole: Download: copy file error
05-04 22:34:57.294 10624 10624 D AndroidRuntime: Shutting down VM
--------- beginning of crash
05-04 22:34:57.295 10624 10624 E AndroidRuntime: FATAL EXCEPTION: main
05-04 22:34:57.295 10624 10624 E AndroidRuntime: Process: io.sanford.wormhole_william, PID: 10624
05-04 22:34:57.295 10624 10624 E AndroidRuntime: java.lang.IllegalArgumentException: File doesn't exist: /storage/emulated/0/Download/README.md
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.content.ContentResolver.insert(ContentResolver.java:1831)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1530)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1400)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at io.sanford.wormholewilliam.Download.onAttach(Download.java:85)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1247)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2037)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.app.BackStackRecord.commitNow(BackStackRecord.java:656)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at io.sanford.wormholewilliam.Download$1.run(Download.java:46)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7397)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-04 22:34:57.295 10624 10624 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
05-04 22:34:57.337 10624 10624 I Process : Sending signal. PID: 10624 SIG: 9
```

**Comment by psanford** [comment]
Ah, that error log helps a lot. Let me see if I can figure out why that is happening on some devices.

**Comment by psanford** [comment]
I just pushed a new version v1.0.4rc1: https://github.com/psanford/wormhole-william-mobile/releases/tag/v1.0.4rc1

That includes WRITE_EXTERNAL_STORAGE and some additional debug information for when writing the file fails. You can test this by installing it via adb: 
```
adb install wormhole-william.release.apk
```

I've also published this as a pre-release on the Play Store if it is easier for people to test. Please test and let me know if this helps.

**Comment by psanford** [comment]
Is anyone who is experiencing this issue able to assist in testing this new apk? I don't have access to any phones that are demonstrating the problem (stock Pixels don't manifest this issue) so I'll need some help from someone who has a device that is having this issue on 1.0.3

**Comment by pepa65** [comment]
Sorry, can't find this file, it doesn't show up when I browse to this URL.

**Comment by ashwinvis** [comment]
@psanford installed version 1.0.4rc1 as you directed. Manually provided "storage" permission. Still crashes on receive.

```log
❯ adb logcat --pid=13202                     
--------- beginning of main
06-03 10:20:06.973 13202 13202 E ormhole_willia: Not starting debugger since process cannot load the jdwp agent.
06-03 10:20:07.006 13202 13202 I Perf    : Connecting to perf service.
06-03 10:20:07.066 13202 13222 I AdrenoGLES: QUALCOMM build                   : 994be9a, I75b52107df
06-03 10:20:07.066 13202 13222 I AdrenoGLES: Build Date                       : 05/28/20
06-03 10:20:07.066 13202 13222 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.10
06-03 10:20:07.066 13202 13222 I AdrenoGLES: Local Branch                     : 
06-03 10:20:07.066 13202 13222 I AdrenoGLES: Remote Branch                    : 
06-03 10:20:07.066 13202 13222 I AdrenoGLES: Remote Branch                    : 
06-03 10:20:07.066 13202 13222 I AdrenoGLES: Reconstruct Branch               : 
06-03 10:20:07.066 13202 13222 I AdrenoGLES: Build Config                     : S L 8.0.12 AArch64
06-03 10:20:07.070 13202 13222 I AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
06-03 10:20:07.097 13202 13230 W Gralloc3: mapper 3.x is not supported
06-03 10:20:38.927 13202 13228 I io.sanford.wormhole_william: recv clicked
06-03 10:20:43.637 13202 13225 I io.sanford.wormhole_william: Call NotifyDownloadManager
06-03 10:20:43.640 13202 13225 D wormhole: Download()
06-03 10:20:43.641 13202 13225 D wormhole: Download: register()
06-03 10:20:43.642 13202 13202 D wormhole: Download: onAttach()
06-03 10:20:43.648 13202 13202 D wormhole: Download: copy file error: java.io.FileNotFoundException: /storage/emulated/0/Download/README.md: open failed: EACCES (Permission denied)
06-03 10:20:43.664 13202 13202 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-03 10:20:43.665 13202 13202 E AndroidRuntime: FATAL EXCEPTION: main
06-03 10:20:43.665 13202 13202 E AndroidRuntime: Process: io.sanford.wormhole_william, PID: 13202
06-03 10:20:43.665 13202 13202 E AndroidRuntime: java.lang.IllegalArgumentException: File doesn't exist: /storage/emulated/0/Download/README.md
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.content.ContentResolver.insert(ContentResolver.java:1831)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1530)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1400)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at io.sanford.wormholewilliam.Download.onAttach(Download.java:83)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1247)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2037)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.app.BackStackRecord.commitNow(BackStackRecord.java:656)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at io.sanford.wormholewilliam.Download$1.run(Download.java:45)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7397)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-03 10:20:43.665 13202 13202 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
06-03 10:20:43.702 13202 13202 I Process : Sending signal. PID: 13202 SIG: 9
```

**Comment by ashwinvis** [comment]
@pepa65 There are some extra steps in configuring adb. On the phone you need to [enable USB debugging ](https://developer.android.com/studio/debug/dev-options) and [on the laptop hopefully this helps](https://wiki.archlinux.org/title/Android_Debug_Bridge#Usage).

**Comment by psanford** [comment]
Good News Everyone! I was able to reproduce this error in the android emulator using an android-10 image. (It worked fine on android-11 in the emulator).

I've got a fix which works in the emulator so hopefully it will work for everyone on android 10 experiencing this issue. 

I've uploaded another rc version for testing on real devices: https://github.com/psanford/wormhole-william-mobile/releases/tag/v1.0.4rc2 

Please let me know if this fixes the issue for you.

Here's what the flow looks like running on Android 10 from the emulator:
https://user-images.githubusercontent.com/33375/121828775-6acd2000-cc75-11eb-9cb2-dacfe9e64a4f.mp4

**Comment by thelazyoxymoron** [comment]
Thank you so much, this works as expected now!

**Comment by ashwinvis** [comment]
It works!

**Comment by psanford** [comment]
I've released v1.0.4 final. Its been approved and is available on the Play store.
